### ISSUE TITLE
Request support for dynamic version number, copyright year, custom progress bar style, and Cancel button on splash screen

### ISSUE THREAD

**Issue by ViksitAgarwal** [velopack/velopack#102]
Hello Velopack Team,
We have chosen Velopack to replace Wix installer for our desktop app. While Velopack looks amazing in its features, especially the auto-update functionality, but there are some minor limitations which are falling short of our requirements and expectations.  There is a support to show splash screen during installation, we would like support for the following in splash screen:

1. Dynamic text on top of splash screen, for example: Version number, Copyright year information etc.
2. Custom style for installation progress bar instead of thick green bar which is not aligned our UX standards.
3. Have a Cancel button rendered at some appropriate place (preferably bottom right corner) to Cancel the installation, if user chooses to cancel the installation while it is in progress.
4. Support of localization of default text shown in the installer UI.

The below sample splash screen shows an example of our expectations.  Please suggest ways to achieve it if already possible or priortize to support these enhancement requests. 
![image](https://github.com/velopack/velopack/assets/93319216/079a8e58-35d3-494f-9ab0-306578cb792c)

**Comment by caesay** [comment]
Hi there, and thanks for checking out Velopack. 

Velopack is a project that I currently develop for free in my spare time, and this is a fairly specific request for customisation which is clearly intended to support a commercial product with specific branding guidelines. I don't have any specific plans at the moment to allow this level of customisation in our setup or updater. 

I do intend to support localization via https://github.com/velopack/velopack/issues/60 but it will only be supported for the built-in designs/screens and I don't intend to allow developers to provide their own localisation text (because the screens won't be customised anyways).

If your company would like to commercially sponsor the project I would be more than happy to reconsider the above points and/or discuss building a custom branded solution for your company. My email is on my github profile, feel free to get in touch.
