### ISSUE TITLE
Supporting Additional code to be run as Administrator during installation

### ISSUE THREAD

**Issue by samdubey** [velopack/velopack#103]
During WPF Application installation on Windows, I want add https://github.com/JamieMcManus/CustomProtocolAppExample, Which needs application to be run as Administrator

Installer to run additional C# code for make such things possible, this required only once for installation

How would i do that?

**Comment by caesay** [comment]
Velopack does not currently support running any administrative processes or code. If you want to do it you need to do it yourself eg. when your app first runs. However, you do not need admin to register a custom protocol. That sample is installing to ClassesRoot hive (which requires admin and installs for all users) but that does not make sense since velopack apps are only installed for the local user. Please install your registry entries to HKCU instead, which does not require admin, and remember to clean them up when your app is uninstalling.
