### ISSUE TITLE
How to upload to a folder on github?

### ISSUE THREAD

**Issue by leaderanalytics** [velopack/velopack#124]
I am releasing my app for both Windows and Linux.  How do I upload each release to their respective release folder on github?
Desired is `https://github.com/my/release/windows` and `https://github.com/my/release/linux`
I've tried `https://github.com/my/release/windows` in the `repoUrl` argument however this fails.

Here is my upload script:

    vpk upload github --repoUrl https://github.com/my --publish --releaseName "AppName" --tag v1.0.0 --token $(github-token) 

Edit:
I think I might need same for ` vpk download github --repoUrl https://github.com/Myname/Myrepo`

**Comment by caesay** [comment]
There are no folders in github releases, it's just a list of assets. You should use a different channel for each operating system (eg. `--channel linux-x64`) and then upload them to the same github release. The two channels will be differentiated because releases for different channels have different filenames.
