### ISSUE TITLE
Downloaded nupkg isn't removed from /var/tmp/velopack on linux after update

### ISSUE THREAD

**Issue by AArnott** [velopack/velopack#129]
The `/var/tmp/velopack/Nerdbank.Zcash.App/packages/Nerdbank.Zcash.App-0.3.73-beta.gb3acab83e3-ci-linux-x64-full.nupkg` file that the self-updater downloaded was successfully applied on my linux machine, but the updater never went back to delete that nupkg. Presumably that will just accumulate update files and clutter the machine.

**Comment by caesay** [comment]
It will only keep 1 previous package around, it will not accumulate multiple packages.

So one issue we have for delta package is that we need the old `.nupkg` around. On windows, this is okay because the app dir is writable. On macos, this is currently a problem (we store to ~Library) but I plan to embed the .nupkg inside the newly extracted .app bundle _before_ we copy it to `/Applications` so it's deleted with the app. On linux though, the `.AppImage` is not writable and there is no guarantee that the tools we need to modify the bundle are on the target system. I'm open to suggestions on where we can store this file.

**Comment by AArnott** [comment]
If you just store one, that seems reasonable. I should have waited for evidence of more than one package before reporting. Thanks.
