### ISSUE TITLE
On linux, AppImage update console output prints *over* the shell prompt

### ISSUE THREAD

**Issue by AArnott** [velopack/velopack#131]
When the app restarts for an update, velopack is evidently printing to the console beyond the time that the shell expects it to. Possibly because velopack waits for the parent process (the app) to exit before applying the patch. But as a result, you get this weird output:

<img width="1137" alt="image" src="https://github.com/velopack/velopack/assets/3548/dd5f9d44-db7f-48da-a035-d0525afb0fc1">

Notice how the shell prompt is buried amidst the velopack logs. I seriously waited about two minutes for the shell prompt to appear, wondering why the update was taking so long to exit after the "applied successfully" message, before hitting "enter" to check whether the shell prompt would just appear, which it did. *Then* I found the shell prompt buried elsewhere in the log.

I've seen other linux utilities suffer from this, and I don't know what the fix would be, since you _do_ need to wait for the parent process to exit (I suppose). But it's a usability issue, so thought I'd raise it.

**Comment by caesay** [comment]
I don't think we can fix this issue -- The shell returns a prompt as soon as the first appimage exits, but there are other processes running at that point (eg UpdateNix and the updated app)

**Comment by AArnott** [comment]
Just brainstorming here... since you say that linux lets you replace executables while they are running... what if you _don't_ wait for the AppImage to exit before servicing it. In fact, what if you deliberately hold up that process from exiting (through code running in that process) while you update?

**Comment by caesay** [comment]
Yes it's of course possible, but I don't think it's worth. How will the running appimage know when the update has finished and it's safe to exit? Also, the newly started image on the new version will _still_ be overwriting the console. Unless we leave the old version running forever? Also, AppImage's are desktop apps, I expect they'll usually be started by clicking them in the appbar, desktop, etc - rather than being started by command line.
