### ISSUE TITLE
Better Azure Trusted Signing Support

### ISSUE THREAD

**Issue by caesay** [velopack/velopack#142]
It's currently a bit of a hassle to use Azure Trusted Signing with Velopack (getting the right version of signtool, dylib, etc). I think we should ship a new cli parameter like `--azTrustedSign {metadata.json}` which takes your Azure Trusted Signing config and configures signtool.exe for you.

**Comment by LiamDHall** [comment]
I have move our whole stack to use Velopack, it is a breeze compared to other installers. I am just looking in to using Azure Trusted Signing now.
Please can you point me in the right directions for the current implementation using Azure Trusted Signing. Preferable via GitHub Actions

**Comment by caesay** [comment]
I suspect this is a bug in Azure Trusted Signing. You can try `--signParallel 1` to disable signing in parallel (to rule that out as an issue) and you can also use `--signSkipDll` to only sign .exe files. Please let me know which one (or both) that fix the issue.

**Comment by caesay** [comment]
Also note that  you can use the `--verbose` argument to get additional output (eg. which file/files failed to sign). And Velopack will not attempt to re-sign stuff which is already signed, so if there is a binary in particular which is having issues when being signed by Velopack you can sign it ahead of time before you run `vpk pack`.

**Comment by LiamDHall** [comment]
I tried signing all the dll before packing but then i failed on the Squirrel.exe
![image](https://github.com/user-attachments/assets/7366a823-e114-4e75-bd25-270600e2f053)
I will try with your suggestions and let you know

**Comment by LiamDHall** [comment]
I have tried with  {{file...}}" --signParallel 1 and  {{file}}" --signParallel 1 both have caused the same issue
as I have signed all the dll beforehand and its failing on Squirrel.exe I have not tried --signSkipDll

**Comment by LiamDHall** [comment]
I'm also not sure how to pre sign the Squirrel.exe as it does not appear in my publish folder

**Comment by caesay** [comment]
Squirrel.exe is the velopack update binary bundled with your app. It's included and signed every time you run `vpk pack`. 

I thought you said that the signing works successfully when packing self contained? Update/Squirrel.exe would be the same in both cases. Can you run it with/without self contained with `--verbose` on so we can see the different arguments being passed to signtool in both cases?

**Comment by LiamDHall** [comment]
Otherwise around, apologies if that was not clear:

1. when **NOT** --self-contained i.e. (dotnet publish -c Release -r win-x64 -o .\publish) **signs everything successfully** 

2. when when --self-contained i.e (dotnet publish -c Release --self-contained true -r win-x64 -o .\publish) **fails**

Originally the --self-contained signing was failing on signing NuGet Package dlls, so then pre signed them beforehand, but now its failing on Update/Squirrel.exe and I don't have a file path to it to pre sign before running the vpk pack command.

I will screenshot the verbose output and share it with you.

**Comment by caesay** [comment]
I'm running out of suggestions. I guess use --verbose to see the command that Velopack runs (which fails) and copy that command and run it in your terminal. Also double check that you have the latest .net 8.0 sdk installed I guess. You could try using a different signing tool (eg. `--signTemplate` with `dotnet sign` which also supports trusted signing)

**Comment by madorjan** [comment]
I have the same problem. "Trusted Signing" of a self-contained build always fails with:

![grafik](https://github.com/user-attachments/assets/5a92a4b1-7c6a-49f7-9e86-ef0c94655dc4)

SDK 8.0.401
vpk 0.0.610

Signing with a locally installed certificate works, regardless of self-contained build or not.

Maybe some package version inconsistencies?

**Comment by caesay** [comment]
This is an issue on the Azure Trusted Signing side, but a workaround has been added in Velopack to fix this in https://github.com/velopack/velopack/releases/tag/0.0.630-g9c52e40 - @madorjan @LiamDHall if you are still having issues please retry with this latest version.

**Comment by madorjan** [comment]
Signing works with included signtool and following option:

`--signParams "/fd SHA256 /tr http://timestamp.acs.microsoft.com /td SHA256 /dlib \"C:\Users\user\.nuget\packages\microsoft.trusted.signing.client\1.0.60\bin\x64\Azure.CodeSigning.Dlib.dll\" /dmdf \"absolute\path\to\signingInfo.json\""`

So the problem was that the paths of the files to sign were not absolute paths? Hmmm, strange...

**Comment by caesay** [comment]
Using absolute paths is a workaround. We were using relative paths for a reason, but the issue is that signtool.exe was loading an incompatible dotnet version from the publish/output directory instead of from the system dotnet install.

**Comment by madorjan** [comment]
I implemented a `--azTrustedSign` parameter as suggested above. How should we distribute the CodeSigning.Dlib? Within the vendor folder like the signtool.exe?

**Comment by caesay** [comment]
Good question. The Dlib is actually not a single DLL, but a collection of 10-15 dll's if my memory is correct. That is a lot to redistribute in vendor. Can you open a draft PR with your changes so far and I'll discuss it with @Keboo?

**Comment by madorjan** [comment]
You are right, unfortunately its not just a single DLL. Maybe we could access it using the https://www.nuget.org/packages/Microsoft.Trusted.Signing.Client package. I'll open a PR and we can discuss it there.

**Comment by smoogipoo** [comment]
It's very nice to see this getting some traction! We've also recently switched to Velopack+ATS via the `signTemplate` arg. If you'd like another data point, here's what was involved for us: https://github.com/ppy/osu-deploy/pull/176

Importantly, I don't believe we ever got ATS to work with Velopack's included signtool. From my recollection, we were able to sign locally but encountered weird errors when run in a GitHub workflow.

Since we always build on a GHA runner, we swapped to using the signtool from the included Windows SDK. While not versioned so an update to the runner could break things, it works for now and is what [gh-cli does](https://github.com/cli/cli/blob/76ea9396275ac5a79d62f6987303b7e12b147ff9/script/sign.ps1#L13-L14). Later I found that the [ATS action](https://github.com/Azure/trusted-signing-action/blob/07c81171dd46a04e1b9f382b6c693815828bbbf7/action.yml#L212) mentioned in the Microsoft article pulls signtool from another nuget package: https://www.nuget.org/packages/Microsoft.Windows.SDK.BuildTools/10.0.22621.3233.

It's possible that we were doing something wrong and the later fix (https://github.com/velopack/velopack/pull/242) supersedes the signtool change. It'll need more testing, but if the included signtool truly doesn't work on GHA then you could consider doing the same (since you have to download the dlib anyway), or update the included binary.

As for why it didn't work - I recall something along the lines of Windows version differences, but I don't think we investigated beyond that. What I can say for sure is that Velopack uses the signtool from `10.0.22621.2428`:

```sh
cd8015e0de5f7aff52ea1971f58c7853ad7b53380b5bed685b60de76947cd9fa  signtool.exe
dac3d1cd1c6ff9bb4cb0172f13d373eb2407d40c32093a2053f4a7fb47488224  1/bin/10.0.22621.0/x64/signtool.exe
3827603c7015c047afe8259f4e94366955499af490b76f4ac18e13f2df700d85  755/bin/10.0.22621.0/x64/signtool.exe
3827603c7015c047afe8259f4e94366955499af490b76f4ac18e13f2df700d85  756/bin/10.0.22621.0/x64/signtool.exe
cd8015e0de5f7aff52ea1971f58c7853ad7b53380b5bed685b60de76947cd9fa  2428/bin/10.0.22621.0/x64/signtool.exe
8cfd7441d53c3418ec4ca4436644020f7a1a4a9ccb7d102aed53a61e2a89e405  3233/bin/10.0.22621.0/x64/signtool.exe
```

**Comment by Keboo** [comment]
@smoogipoo great info. Yes there is a versioning issue with the current one (an issue we are fixing). Working on some tests then will be getting this merged.

**Comment by caesay** [comment]
This has been released
