### ISSUE TITLE
Unable to Update. Downloads to 10% and stops.

### ISSUE THREAD

**Issue by NorMoll** [velopack/velopack#146]
Would appreciate some advice please.

I have an Avalonia 11 Desktop app and cannot upgrade successfully when the update files are hosted online (https://website/webroot/downloads) but when the same files are placed in a local folder the update succeeds.

Vpk also seems to generate a file as large as the original win-Setup file even though I've only made a small change. So the question is whether I need to always upload the large 1.0.x-full.nupkg or should the -delta.nupkg file suffice?

![Velopack Log](https://github.com/velopack/velopack/assets/133159180/1178e5f9-b29b-4810-b6ad-25a608b0397f)

**Comment by caesay** [comment]
> So the question is whether I need to always upload the large 1.0.x-full.nupkg or should the -delta.nupkg file suffice?

You always need to upload the `-full.nupkg`, `-delta.nupkg` and also `releases.{channel}.json`. It's not supported to only publish delta's. Also, your `releases.{channel}.json` file needs to accurately reflect what files are available in that destination. So `https://website/webroot/downloads/releases.{channel}.json` should have a list of the files which are available at `https://website/webroot/downloads/` (including a -full and a -delta for every release).

Your users, if possible, will download only delta's, and usually will not need a full release, but there are cases in which full releases are required, and there are parts of Velopack which will disregard/ignore a delta if there is no accompanying full release.

I can't see anything wrong in your logs, it looks like the update succeeded? ("Failed to extract new Update.exe" is a warning, it will not fail the update).

**Comment by NorMoll** [comment]
Thanks so much for the prompt reply.

I reverted back to v1.0.0 and changed to a local downloads folder. Installed and immediately made a code switch to simulate a change and ran the following:
dotnet publish -c Release --self-contained -r win-x64 -o .\publish
then
vpk pack --delta BestSize -u "MyApp.Desktop" -v 1.0.1 -p .\publish -e MyApp.Desktop.exe
Ran the app, Checked for Download avaliable which there was. Downloaded (0~100% ok) Apply button active, applied the update and all worked as expected.

I then followed exactly the same procedure to the ~/webroot/Downloads folder and as before get the indication that Download is available. I then select Download and progress goes to 10% and nothing happens after that. Button to Apply remains disabled. Restart app, retry Check for Download, this time I don't even get the 10% indication.

Any ideas will certainly be appreciated.

**Comment by caesay** [comment]
That doesn't sound like any known issues I'm afraid. I'm assuming you are capturing UpdateManager logs, and nothing beyond your earlier screenshot is available? Are any exceptions happening?

If nothing above sounds relevant, perhaps try adding `.ConfigureAwait(false)` to the end of your velopack check/download functions - if there is an issue with your sychronisation context then it might be deadlocking. 

If ConfigureAwait also does not help, can you please upload a sample app to GitHub for me to look at?

**Comment by NorMoll** [comment]
Hi there,

Thanks for the response again. 

Setting ConfigureAwait(false) crashes the app. I've created a test app and the same happens in this app when I point it to mysite/wwwroot/downloads. i.e. it gets to 10% then fails.

Have no idea how to implement IVelopackLocator but perhaps the app below will assist in getting it sorted.

https://github.com/NorMoll/VelopackTest

Thanks again for the assistance.

**Comment by caesay** [comment]
> Setting ConfigureAwait(false) crashes the app.
Probably because there is code afterwords that needs to be dispatched back on to the UI thread (eg. `UpdateStatus`). 

I tested the sample app (using a local HTTP server) with both 0.0.359 and 0.0.541 and all seems to work fine for me. 

All I did was:
- Open your `.sln` in Visual Studio
- Hit F6 to compile
- Navigate to `bin/Debug` folder in the desktop project 
- Run `vpk pack -u VelopackTest.Desktop -u 1.0.0 -p net7.0`
- Navigate to `./Releases` (where Velopack output is, and started local HTTP server running at `http://127.0.0.1:8080`)
- Replace your `UPDATEPATH` with the above URL, build a new release (1.0.1)
- Install the latest release (1.0.1)
- Build yet another release (1.0.2)
- Verify that app can successfully check for, download, and update.

Then I did the whole thing again on the latest Velopack version and it all worked there too.

I would still try to get `ConfigureAwait(false)` working to rule out an Avalonia/threading deadlock issue, and the next place I'd look is if your update source `https://website/webroot/downloads` is doing something weird. The fact it stops at 10% means it's probably an async deadlock.

**Comment by NorMoll** [comment]
Hi there,

As I mentioned it works to a local folder. The problem is when you publish it remotely so may be download speed related.

**Comment by caesay** [comment]
I tested with an HTTP source (rather than local file) and it all works fine. We also have integration tests in this repo that round-trip the updates through Azure Storage. The fact it stops at 10% and fails is almost certainly an async deadlock, specifically possibly here: https://github.com/velopack/velopack/blob/develop/src/Velopack/UpdateManager.cs#L268 we log 10% progress and then make our first async call which presumably just never returns. 

I likely won't be able to help further unless you can provide more info. Please test the async bits w/ ConfigureAwait(false), maybe change your remote to something else (eg test with a local HTTP server, or with github releases).

**Comment by NorMoll** [comment]
Hi there.

Just a update really. 

When I connect to a locally created web server the update works fine. I've attempted to implement the false with try/catch, checking that I'm on the UI thread, etc and the Download/Update still crashes the app with an "unknown" message in the Event Viewer. I will try spin my own installer / updater for now but hope this will be sorted in future as you have a really nice solution.

**Comment by caesay** [comment]
Thanks for the update. Since I wasn't able to reproduce this in your sample app and you've not provided any error messages it's unlikely I'll be able to look into this further. But please do let me know if you manage to find any additional info and I'd be happy to re-open this

**Comment by caesay** [comment]
If you can get it working with a local http server, but not with your "remote" server, then I'd suspect there might be something wrong with your remote so might be worth uploading somewhere else instead.
