### ISSUE TITLE
Allow skipping the VelopackApp builder check

### ISSUE THREAD

**Issue by jaselee0905** [velopack/velopack#17]
I had no problem previously making builds for my wpf application but now I get this error
<img width="1103" alt="Screenshot 2024-01-29 at 5 41 08 PM" src="https://github.com/velopack/velopack/assets/41090702/320c2dc3-3590-42f4-b15a-d8e2525b3f4c">
The only change I made was updating the velopack version to the latest.

My project generates its main() so I cannot add VelopackApp.Build().Run() to it, but I put it in the startup function that is defined in the app.xaml and it worked fine before but not anymore

When it was working I was on velopack version 0.143

**Comment by leonidcan** [comment]
+1 I am trying to build alternate installer/updater using velopack, before I was able to put VelopackApp.Build... into conditional if later in the app. Can we have an option to not validate the app?

**Comment by caesay** [comment]
There is a WPF sample which shows how to add an explicit Program.Main() to your app https://github.com/velopack/velopack/tree/master/examples/VeloWpfSample but I'm not opposed to adding an environment variable which disables the check.

**Comment by leonidcan** [comment]
>  I'm not opposed to adding an environment variable which disables the check.

Or better a command line parameter, this will simplify CI/CD pipelines

**Comment by caesay** [comment]
It is easy to add env variables to CI/CD, certainly not any harder than adding a CLI argument! Regarding adding a CLI parameter, I am trying to keep down on the number of new parameters added especially when it's a niche use case like this. I expect in 99% of scenarios (incl WPF) that the VelopackApp builder should be in your Program.Main. When there are too many available arguments, it becomes impossible for a new user to use the command line help to discover _actually useful_ new features. 

The reason the check exists, is if you mess this up it leads to some very weird and unfortunate bugs on Windows. With Clowd.Squirrel (the previous iteration of Velopack), people would miss adding this check constantly and then come to me complaining about unhappy users and/or bugs in my software.

I am hoping that having this check be the default will go un-noticed by pretty much anyone who follows the documentation, and adds the check to Program.Main. The WPF sample also explains how to do this in that case also. However, if someone has a real and legitimate use-case for not implementing the VelopackApp builder I agree that a "hidden" or "out of the way" option should be available.

**Comment by caesay** [comment]
There was a different kind of check in earlier versions of Velopack. The original check would start your program with the argument `--veloapp-version` and expect it to respond and exit with a specific message. However, this check needed to be removed because it did not work if you were cross-compiling (for example, you compiled an arm64 binary on an x64 computer, and now the binary can not be started). So it has been replaced with this check, which does not need to start the binary to run, it's just a simple IL check to see if the `Run()` method is called from your Program.Main (which is where it should be). 

The original version of this check would have potentially worked if you had the VelopackApp code in some other method instead, however there were lots of other problems with it - so this solution should be a lot more stable going forward.

**Comment by caesay** [comment]
And additionally, running the VelopackApp.Build().Run() method from within a WPF `Application.OnStart` or similar might technically work (and would have been allowed with the previous check) it means that the WPF application pipeline has to start up before VelopackApp can receive messages and potentially exit. Two of these hooks are run during each update, so I could imagine that taking up several/many precious seconds on a slower computer, whereas if the check was earlier (eg. Program.Main) WPF would not need to be involved.

**Comment by caesay** [comment]
There is now a command line argument and an environment variable available to skip this check. 

`--skipVeloAppCheck` / `VPK_SKIP_VELO_APP_CHECK`
