### ISSUE TITLE
How to deploy appsettings.json to users roaming folder?

### ISSUE THREAD

**Issue by sam-wheat** [velopack/velopack#183]
I want to deploy my app's  `appsettings.json` file to users roaming folder as described [here](https://docs.velopack.io/integrating/preserved-files).  

I have an app that I published using version 0.0.359 and the `appsettings.json` file automagically got deployed to the right place.

Now I'm publishing a new app using version 0.0.556 and the `appsettings.json` file is only copied to the same folder as the .exe.

How do I configure Velopack to do this?

**Comment by caesay** [comment]
What are you using to create an `appsettings.json`? You can't configure Velopack to do anything regarding settings files, there's nothing special or magic in Velopack which would have deployed your settings to a special place. With whatever framework/library you use to load/save settings, you should configure it to persist to roaming app data instead of the exe directory.
