### ISSUE TITLE
How to update a console app?

### ISSUE THREAD

**Issue by sam-wheat** [velopack/velopack#188]
My app is a console app - user opens a command window and runs myapp.exe.

In my app I call `CheckForUpdatesAsync`, an update is found and it installs.  However I get an error message from Windows that the app must be closed manually - is this because the command window is open?

![image](https://github.com/user-attachments/assets/56c7e3b7-a27e-4497-8e86-3206bfd310ed)

**Comment by caesay** [comment]
By this point your application is probably not running, and you are seeing this window because the _working directory_ of cmd.exe is inside the `%localappdata%/YourAppId/current` directory. If you run `cd ..` and try your update command again (eg. `./current/yourapp update`) I suspect it will work fine. Ideally, I'd expect you'd add your console app to the system PATH to avoid this problem. There's also https://github.com/velopack/velopack/issues/38 where someone suggested some other console-related improvements.
