### ISSUE TITLE
Including only some files

### ISSUE THREAD

**Issue by stefanolson** [velopack/velopack#2]
I'm upgrading from Clowd.Squirrel 3.0, which I haven't yet shipped to customers, so I thought I would upgrade to this before shipping to customers later this week, as I've been so impressed with Clowd.Squirrel. just worked perfectly so far in my testing.

However it does seem to be designed a little differently. 

Few points:
1. In the previous version I could specify an already built nupkg file. This is useful to me because I can then choose which files I want to include. I just tried to do a .net publish and there's all sorts of stuff in there that I don't want..  Can I just put what I want in a folder to use?
2.  Did try and compile it using vpk, but I am building a WPF application and thus have no Program.Main, so it doesn't work "Failed to verify VelopackApp. Ensure you have added the startup code to your Program.Main(): VelopackApp.Build().Run();"
3. I can't find a way to get my application signed, even if I could compile it. Doesn't seem to be any sort of signing parameters on the command line? As with Clowd.Squirrel, I only want to sign EXE's and not DLLs, presume that's a pack parameter
4. The previous version had commandline parameters that allowed me to do certain things when it was being installed or uninstalled . Are those available somehow as I need to install other programs and set up my  application icons 

fyi: I'm seems like I'm running Velopack CLI 0.0.64-g250b6b8 currently.

Am I best just to ship with Clowd.Squirrel 3.0 for the moment?

Thanks!

**Comment by caesay** [comment]
1. at the moment not possible, no. when writing your build script I imagine you can delete the files you don't want before bundling? however I could consider adding some "exclude" parameters in the future. 
2. You can create a program.main in wpf, there are several ways - one of which is described here. https://www.meziantou.net/creating-a-custom-main-method-in-a-wpf-application.htm - I plan to also supply a WPF example app shortly. The other option, is to override OnStartup in your Application class - although since this happens later in your app startup it might be a bit slower. 
3. All the same signing parameters should be as before, can you share the output of "vpk pack -h" with me? 
4. Yes, all of this is still possible, please check the methods available on `VelopackApp.Build()`

Clowd.Squirrel 3.0 had some unresolved issues, Velopack is better designed and better tested - I apologise for any pains you're having getting set up.

**Comment by caesay** [comment]
You should see something like this - same signing parameters as before. 
![image](https://github.com/velopack/velopack/assets/1287295/283e0fb2-ae8a-4d7f-9cda-fbbd7a4e93f1)

**Comment by stefanolson** [comment]
Thanks. Partway through my reply...

1. Copying files to a folders seems to work fine, so that will work for me.
2.  Followed your instructions and that works fine.
3. ah, found  the command line parameters by accidentally putting in an invalid one. I tried this and didn't get the pack details:
PM> vpk -pack -h
Description:
  Velopack CLI 0.0.64-g250b6b8 (prerelease) for creating and distributing releases.

Usage:
  vpk [command] [options]

Options:
  -?, -h, --help  Show help and usage information
  --version       Show version information
  --verbose       Print diagnostic messages.

Commands:
  pack      Creates a release from a folder containing application files.
  download  Download's the latest release from a remote update source.
  upload    Upload local package(s) to a remote update source.
  delta     Utilities for creating or applying delta packages.

**Comment by stefanolson** [comment]
Continuing..
4. That seems to work fine. I'll now test it in an actual application

>>Clowd.Squirrel 3.0 had some unresolved issues, Velopack is better designed and better tested - I apologise for any pains you're having getting set up.<<

No problem at all, obviously early days with this new release, so not expecting everything to be perfect yet. Thanks for all the work you've put into improving it. It is such a great way to install.

**Comment by caesay** [comment]
Closing this for now, as it seems you've resolved all your questions. Let me know if I can be of any further help and I can re-open this. You can also pop in our Discord if you just have some quick questions it might be faster.
