### ISSUE TITLE
Deprecated Microsoft.Extensions.Logging.Abstractions 2.2.0.0 is installed

### ISSUE THREAD

**Issue by KotM** [velopack/velopack#203]
### OS

Windows Feature Experience Pack 1000.19060.1000.0

### Programming Language

.NET Framework 4.8.1

### VPK Version

vpk             0.0.583

### Library Version

Velopack.0.0.583

### What happened?

After installing Velopack.0.0.583 to Windows Desktop application it installs Microsoft.Extensions.Logging.Abstractions.2.2.0, which is deprecated for a long time (latest version is 8.0.1).

**Comment by caesay** [comment]
Intended. 

On full NetFramework, our package dependency looks like this:
```xml
<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="[2.2.0,)" />
```

On net6 and net8 our dependency looks like this:
```xml
  <ItemGroup Condition=" $(TargetFramework) == 'net6.0' ">
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="[6.0.0,)" />
  </ItemGroup>

  <ItemGroup Condition=" $(TargetFramework) == 'net8.0' ">
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="[8.0.0,)" />
  </ItemGroup>
```

That syntax `[2.2.0,)` means the minimum version is 2.2.0 but that we also support anything newer than this. The reason we do this is because new versions of `Microsoft.Extensions.Logging.Abstractions` require `System.Memory` etc, which brings in A LOT of dependencies for poor Full NetFramework projects.

For people already on dotnet6/8, `System.Memory` is built into the runtime and so does not bring any further dependencies. 

If you would like to bring in a more recent version of the library into your Full NetFramework project (including all the other dependencies that it brings etc) then you're welcome to do so by adding your own reference to the Microsoft.Extensions.Logging.Abstractions package and choosing a more recent version.
