### ISSUE TITLE
User-created files in %LocalAppData%/MyApp get deleted on update/reinstall ?

### ISSUE THREAD

**Issue by quacrobat** [velopack/velopack#25]
If I understand correctly, the default installation goes to %LocalAppData%/MyApp.

And it seems to me that the entire MyApp folder is removed on update or uninstall or reinstall.

This generates an unwelcome situation where if MyApp needs to save anything to the %LocalAppData%/MyApp at runtime (eg. customized user settings), these risk being deleted.

Is there a workaround to this without having the change MyApp itself?

Thanks :)

**Comment by caesay** [comment]
The folder is removed on uninstall / install yes. It's not removed/touched on updates. Inside the folder structure you will have `%LocalAppData%\MyApp\current`, and the `current` folder is replaced on updates. So if you store your settings up one folder (`..`) then they will persist through updates. Alternatively, you can store your settings where they probably belong: `%appdata%\MyApp` instead of `%localappdata%\MyApp`. You will need to modify MyApp to store the settings outside of the current dir if you want to persist through updates, or outside of localappdata if you want to persist through re-installs.
