### ISSUE TITLE
Make sq.version filename unique

### ISSUE THREAD

**Issue by ALIENQuake** [velopack/velopack#313]
**Is your feature request related to a problem? Please describe.**
The default filename sq.version is not unique.

**Describe the solution you'd like**
The sq.version file should have unique filename per app, my vote would be to use "$(ApplicationName).version" schema.

**Additional context**
I need to have many sq.version in one place. Right now need to rename each file and then copy it. Having unique filenames would simplified the process.

**Comment by caesay** [comment]
This file can not have a unique name, because an application is expected to only have one of these. Velopack searches the current application folder looking for a file named `sq.version`, and when it is found, that is the manifest which is read to determine the current app ID, version, etc. 

I don't understand your "Additional context". Why do you have these files at all? they are only needed for published applications and they are added by `vpk` automatically.

**Comment by ALIENQuake** [comment]
@caesay Those files are used for reporting/other things after deployment. Making the filename unique would make the pot-process easier.

Besides, even if one app is expected to have one of such file, why It can't be named as application name? Why such arbitrary name, it looks foreign in the same way as 'aq','bt','ou' etc would look. The .NET config files uses "$(ApplicationName).extension" schema so I don't see any reason why Velopack couldn't not use it for it's own configuration.

**Comment by caesay** [comment]
> Besides, even if one app is expected to have one of such file, why It can't be named as application name?

Velopack doesn't know your application name when it starts. I suppose what we could do is look for a file named `*.vpkversion` or something (ignoring the file name). However, at this point, that would massively hurt backwards compatibility because it is a breaking change of a critical part of Velopack - making changes like this always comes with a risk of users bricking their apps during updates if they use the wrong library/vpk version together.

I will add a note to #63 and see if it can be considered as a part of implementing that.
