### ISSUE TITLE
Allow customization of progress bar color

### ISSUE THREAD

**Issue by Noah1989** [velopack/velopack#42]
Currently it is hardcoded here (and a bit harsh on the eyes):

https://github.com/velopack/velopack/blob/138e16973e62c624e7a63dcb9e44fe410e9eb825/src/Rust/src/windows/splash.rs#L229

I assume that will be obsolete anyways with #30?

**Comment by caesay** [comment]
I don't have any plans to add customisation options for the one-click installer at this time. The one-click installer will always be the default installer, but after #30 you will be able to switch between the two, and the wizard will have some amount of configuration options.

Whether or not the green is harsh on the eyes depends on the color / design of your splash image, the user preferences, and so on. It's something you only see once, for a very short time, and it's a better user experience to have some indication of progress rather than the indeterminate gif that you got on Squirrel.
