### ISSUE TITLE
Can't specify version to update to, only the channel.

### ISSUE THREAD

**Issue by LiamDHall** [velopack/velopack#65]
Please make it possible to specify which version of the software to upgrade / downgrade to via the update manager?

Or if I have missed it the documentation please point me in the right direction.

Great work by the by way! An excellent installer.

**Comment by caesay** [comment]
Hi there, the intended way to use UpdateManager is to not specify the version or the channel. The channel is auto-detected based on the package metadata when you build it with `vpk pack`. The version will always be the latest available, which might be lower than the current version if `AllowVersionDowngrade` is set. 

What is your use-case for this? Always helpful to know, so I can consider these things when implementing new features.

I really don't recommend this, but you can implement your own logic by replicating what happens in `CheckForUpdate`. Since these are "internal" API's, they are likely to change frequently with updates to Velopack.

```cs
ILogger logger = null; // create your logger
var locator = VelopackLocator.GetDefault(logger);
var source = new SimpleWebSource("https://the.place/you-uploaded/your/releases");
var feed = await source.GetReleaseFeed(logger, locator.Channel, null, null);
foreach(var a in feed.Assets) {
    System.Console.WriteLine(a.FileName);
}

var targetRelease = feed.Assets.FirstOrDefault(a => a.Version == SemanticVersion.Parse("2.3.4"));
var updateInfo = new UpdateInfo(targetRelease, isDowngrade: false);

// can now carry on with usual update process...
var updateManager = new UpdateManager(source, logger: logger);
await updateManager.DownloadUpdatesAsync(updateInfo);
updateManager.ApplyUpdatesAndRestart(targetRelease);
```

**Comment by LiamDHall** [comment]
Hey, thank you for getting back to me.

It's mainly as a fall back system. If a bug makes it to productions that is stopping people from completing a process but this process is known to be ok in an old version of the software. As a quick fix I could have the user downgraded to the specific version that I know works whilst I create a permanent solution for issue.

**Comment by KotM** [comment]
@caesay unfortunately it is not working as expected, or ever I missing something. 

For example, I'm working with VeloWpfSample. One code line was changed:

`_um = new UpdateManager(updateUrl, new UpdateOptions { AllowVersionDowngrade = true }, logger: Program.Log);`

Also I removed latest version from releases.win.json. I'm able to download it... But it seems like the application is not updated ("Restart" button is not available and after the restart I still getting version .11 instead of expected .10). 

![image](https://github.com/user-attachments/assets/82baefa4-db09-4a4f-8952-f92fc40ffc20)

**Comment by DavidCFreire** [comment]
Hi, i`m just trying to set the user witch version to update to, but i cant get it to work.
My use case is that we need to make different clients to update only to certain version and not newer than that.

For example: Client 1, which is currently on version 1.1.1, needs to be updated to version 1.1.2, but version 1.1.3 has already been released. However, this client should not update to this version.

I tried this solution
> I really don't recommend this, but you can implement your own logic by replicating what happens in `CheckForUpdate`. Since these are "internal" API's, they are likely to change frequently with updates to Velopack.
> 
> ```cs
> ILogger logger = null; // create your logger
> var locator = VelopackLocator.GetDefault(logger);
> var source = new SimpleWebSource("https://the.place/you-uploaded/your/releases");
> var feed = await source.GetReleaseFeed(logger, locator.Channel, null, null);
> foreach(var a in feed.Assets) {
>     System.Console.WriteLine(a.FileName);
> }
> 
> var targetRelease = feed.Assets.FirstOrDefault(a => a.Version == SemanticVersion.Parse("2.3.4"));
> var updateInfo = new UpdateInfo(targetRelease, isDowngrade: false);
> 
> // can now carry on with usual update process...
> var updateManager = new UpdateManager(source, logger: logger);
> await updateManager.DownloadUpdatesAsync(updateInfo);
> updateManager.ApplyUpdatesAndRestart(targetRelease);
> ```
> 
> Also note that this would prevent delta updates from working. The delta strategy is calculated during CheckForUpdates and stored in the UpdateInfo object.


But i keep getting this error
>Could not find asset called 'App-1.2.1072-full.nupkg' in GitHub Release 'Version 1.2.1073'.

**Comment by caesay** [comment]
The error should point you in the right direction... It's searching for asset `App-1.2.1072-full.nupkg` inside the github release `Version 1.2.1073` which presumably does not have that asset. The GithubSource does not support downloading assets from anything other than the latest release currently. Feel free to write your own `IUpdateSource` and/or look at the source code for GithubSource.
