### ISSUE TITLE
Improve error when `pack --framework` is used off Windows

### ISSUE THREAD

**Issue by AArnott** [velopack/velopack#80]
I use Linux build agents whenever I can -- even to build Windows software. This unfortunately led me to try to run `vpk pack` with the `-f` switch, which worked locally for me (on a Windows machine) but repeatedly failed in my Azure Pipelines build. 

```
dotnet tool run -- vpk pack --packVersion 0.2.173-beta.g628b18e325 --channel ci-win-arm64 --packId Nerdbank.Zcash.App --packAuthors Nerdbank --mainExe Nerdbank.Zcash.App.Desktop.exe --packDir /home/vsts/work/1/apps-Windows/win-arm64 --outputDir /home/vsts/work/1/app-packages --framework net8.0-arm64-desktop

Unrecognized command or argument '--framework'.
Unrecognized command or argument 'net8.0-arm64-desktop'.
```

I wasted half a day trying to diagnose why the switch was being rejected. Mostly I was operating on the belief that `dotnet` itself was 'stealing' the switch thinking it was meant for itself, since `--framework` and `-f` are interpreted by some `dotnet` commands.

Eventually I stumbled on the realization that it might simply not be available on linux agents, and so I switched to a Windows agent and it finally worked.

So my suggestion: can you do anything in the error message that is printed to indicate that the argument is recognized but not allowed on Linux?

Also two related questions:
1. Is supporting the switch on linux possible?
2. Given it doesn't work on linux agents, I wonder if that means when I publish my app for linux, _must_ I use `--self-contained` to avoid a runtime dependency, or can velopack acquire the runtime on linux and mac as well as it does on Windows?

**Comment by caesay** [comment]
It looks like you're trying to build a _windows_ rid on a linux os. This is currently not supported. Since you're not providing an `--rid`, the inferred rid was linux, and when building linux apps the command line arguments are different. Perhaps I could add a startup log that makes it clear what OS vpk thinks you're trying to build a package for, to make this easier in CI scenarios. 

That being said, I think this is what you're actually looking for - which will be released in the next pre-release: https://github.com/velopack/velopack/issues/18
