### ISSUE TITLE
Errors when launching .appimage on linux

### ISSUE THREAD

**Issue by AArnott** [velopack/velopack#83]
After building the velopack package for linux, I tried running it (on WSL2). It worked, in that the GUI appeared and everything seemed to function properly. But the terminal I launched it from emitted 3 errors:

```
./Nerdbank.Zcash.App-unpublished-linux-x64.AppImage
cp: cannot create regular file '/home/andrew/.cache/thumbnails/normal/a1f5dad67ac7eb3031956c447b932f9d.png': No such file or directory
cp: cannot create regular file '/home/andrew/.cache/thumbnails/large/a1f5dad67ac7eb3031956c447b932f9d.png': No such file or directory
/tmp/.mount_Nerdba7dsm0Y/AppRun: 7: xdg-icon-resource: not found
```

I haven't set an app icon in the package. Is it looking for an image file that isn't there?

**Comment by caesay** [comment]
AppImage's (and macos .app bundles) _must_ specify an icon, so if you don't provide one to Velopack it just uses a default icon to build the package. 

You shouldn't see those errors on a full linux distro (in theory). There is some code in the Velopack AppRun script which, upon AppImage launch, copies the embedded icon into the system thumbnail cache, so that the embedded icon appears in the taskbar and file explorer. On WSL, there probably is no thumbnail cache or xdg, so it failed to copy the embedded icon into the cache and then failed to find the `xdg-icon-resource` program (asking it to reload icons from the cache) which should be present on a full linux distro.

I guess we could be more graceful about checking for the existence of these things before YOLO'ing command, but you can safely ignore these errors.

**Comment by caesay** [comment]
Here's that AppRun script btw: https://github.com/velopack/velopack/blob/develop/src/Velopack.Packaging.Unix/Commands/LinuxPackCommandRunner.cs#L40-L52

Also note that if you want to build your own custom AppRun / AppDir that's also possible. You can create the necessary files and then feed the AppDir to --packDir instead of your publish directory.

**Comment by AArnott** [comment]
Yes, I think you're right. In particular `$HOME/.cache/thumbnails/normal` and `$HOME/.cache/thumbnails/large` directories do not exist on my WSL environment, and the `cp` command is probably failing due to that.

**Comment by AArnott** [comment]
We have a report of this error appearing on xubuntu as well.
<img width="436" alt="image" src="https://github.com/velopack/velopack/assets/3548/6ddc19d9-5465-411e-93bf-9e7edb506dcf">

**Comment by caesay** [comment]
That warning looks different to the previously reported warnings. It doesn't seem to line up with anything we run in our script:

```bash
if [ ! -z "$APPIMAGE" ] && [ ! -z "$APPDIR" ]; then
    MD5=$(echo -n "file://$APPIMAGE" | md5sum | cut -d' ' -f1)
    cp "$APPDIR/{{iconFilename}}" "$HOME/.cache/thumbnails/normal/$MD5.png"
    cp "$APPDIR/{{iconFilename}}" "$HOME/.cache/thumbnails/large/$MD5.png"
    xdg-icon-resource forceupdate
fi
```

**Comment by caesay** [comment]
I am now thinking that, since these errors can be safely ignored, it might be better to just redirect the command outputs to /dev/null.

**Comment by caesay** [comment]
This will be fixed in the next release

**Comment by AArnott** [comment]
Confirmed on 0.0.523-g5727de1. Thank you!
