### ISSUE TITLE
Add documentation for --skipVeloAppCheck

### ISSUE THREAD

**Issue by Pyritie** [velopack/velopack#88]
Please add something to your documentation about --skipVeloAppCheck, it's necessary for my use case where I have a shared "Installer" class that runs velopack and does some other stuff which all my other apps call from their main methods. I only learnt about this flag from looking through closed github issues.

**Comment by caesay** [comment]
The full list of options (including hidden ones) is available with `vpk pack -H` (note the uppercase -H instead of lowercase). In general, I think if you need to use `--skipVeloAppCheck` you're probably doing the wrong thing. I've relaxed this check a lot in recent pre-releases, it now only checks that you are calling `VelopackApp.Build().Run()` in the same binary as the `--mainExe` which is an absolute requirement of using Velopack unless you write the code to manually handle all the Velopack hooks yourself (but why would you want to do that?)

**Comment by Pyritie** [comment]
I got everything working and installing and updating with `--skipVeloAppCheck` and while having `VelopackApp.Build().Run()` called in a different project, is that unexpected?

**Comment by caesay** [comment]
You can't do that. I don't know if it works in some scenarios but it will definitely break things. Velopack will run your main binary with special command line parameters and environment variables during updates and install. The `VelopackApp` class handles these, perhaps passing data back to the installer/updater, perhaps not. Sometimes it will exit and your process. You must have `VelopackApp` called in the same executable that you indicate with `--mainExe`.

**Comment by Pyritie** [comment]
Ok, I'll try rejiggling some things the next time I work on this.
